const TYPES = {
  LOCAL_STORAGE: 'reduxDots',

  RECEIVE_LEADERS: 'RECEIVE_LEADERS',
  RECEIVE_AUTH_REPLY: 'RECEIVE_AUTH_REPLY',
  COLOR_CHOOSED: 'COLOR_CHOOSED',

  FIELD_SIZE_CHANGED: 'FIELD_SIZE_CHANGED',

  UPDATE_GAME_ROOMS: 'UPDATE_GAME_ROOMS',
  NEW_ROOM_CREATED: 'NEW_ROOM_CREATED',

  WS_MESSAGE_UPDATE: 'WS_MESSAGE_UPDATE',

  PLAYER_JOIN_ROOM: 'PLAYER_JOIN_ROOM',
  PLAYER_SET_DOT: 'PLAYER_SET_DOT',
  PLAYER_GIVE_UP: 'PLAYER_GIVE_UP',
  THIS_PLAYER_GIVE_UP: 'THIS)PLAYER_GIVE_UP',
  GAME_OVER: 'GAME_OVER',
  CLEAR_GAME_FIELD: 'CLEAR_GAME_FIELD',
  INTERRUPT_GAME_COMPONENT: 'INTERRUPT_GAME_COMPONENT',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',
  CLOSE_RESULTS: 'CLOSE_RESULTS',
  SET_MODAL: 'SET_MODAL',
  SET_ACTIVE_PAGINATION: 'SET_ACTIVE_PAGINATION',
  PLAYER_JOIN: 'PLAYER_JOIN',

  /* AUTH */
  LOGIN_REPLY: 'LOGIN_REPLY',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTRATION_REPLY: 'REGISTRATION_REPLY',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',
  LOGOUT_REPLY: 'LOGOUT_REPLY',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  CLOSE_TOAST: 'CLOSE_TOAST',

  /* DOMAIN DATA */
  UPDATE_LEADERS: 'UPDATE_LEADERS',
  UPDATE_LEADERS_ERROR: 'UPDATE_LEADERS_ERROR',
  UPDATE_FREE_ROOMS: 'UPDATE_FREE_ROOMS',

  /* APP DATA */

  /* GAME DATA */
  UPDATE_TMP_COLOR: 'UPDATE_TMP_COLOR',
  UPDATE_PLAYER_ROOMS: 'UPDATE_PLAYER_ROOMS',
  UPDATE_PLAYER_ROOMS_ERROR: 'UPDATE_PLAYER_ROOMS_ERROR',

  /* UI DATA */
  SWITCH_PAGINATION: 'SWITCH_PAGINATION',
  SET_ACTIVE_GAME_TAB: 'SET_ACTIVE_GAME_TAB',

};

export default TYPES;
