export const LOCAL_STORAGE = 'reduxDots';

export const SHOW_AUTH_FORM = 'SHOW_AUTH_FORM';
export const HIDE_AUTH_FORM = 'HIDE_AUTH_FORM';

export const SEND_REGISTER_REQUEST = 'SEND_REGISTER_REQUEST';
export const SEND_LOGOUT_REQUEST = 'SEND_LOGOUT_REQUEST';

export const CHANGE_PLAYER = 'CHANGE_PLAYER';
export const DRAW_DOT = 'DRAW_DOT';
export const CALC_SQUARE = 'CALC_SQUARE';

export const SHOW_SETTINGS = 'SHOW_SETTINGS';
export const HIDE_SETTINGS = 'HIDE_SETTINGS';
export const START_NEW_GAME = 'START_GAME';
export const STOP_GAME = 'STOP_GAME';

export const PLAYER_CHANGED = 'PLAYER_CHANGED';
export const SET_COLOR = 'SET_COLOR';
export const CHECK_FIELD_FULL = 'CHECK_FIELD_FULL';
export const UPDATE_PLAYERS_NAME = 'UPDATE_PLAYERS_NAME';
export const HIDE_RESULTS = 'HIDE_RESULTS';
export const SHOW_LEADERS = 'SHOW_LEADERS';
export const HIDE_LEADERS = 'HIDE_LEADERS';

export const RECEIVE_LEADERS = 'RECEIVE_LEADERS';
export const COLOR_CHOOSED = 'COLOR_CHOOSED';

export const FIELD_SIZE_CHANGED = 'FIELD_SIZE_CHANGED';
export const CALC_CAPTURED = 'CALC_CAPTURED';
export const RESET_PLAYERS = 'RESET_PLAYERS';

export const UPDATE_GAME_ROOMS = 'UPDATE_GAME_ROOMS';

export const TYPES = {
  LOCAL_STORAGE: 'reduxDots',
  SHOW_AUTH_FORM: 'SHOW_AUTH_FORM',
  HIDE_AUTH_FORM: 'HIDE_AUTH_FORM',

  SEND_REGISTER_REQUEST: 'SEND_REGISTER_REQUEST',
  SEND_LOGOUT_REQUEST: 'SEND_LOGOUT_REQUEST',

  CHANGE_PLAYER: 'CHANGE_PLAYER',
  DRAW_DOT: 'DRAW_DOT',
  CALC_SQUARE: 'CALC_SQUARE',

  SHOW_SETTINGS: 'SHOW_SETTINGS',
  HIDE_SETTINGS: 'HIDE_SETTINGS',
  START_NEW_GAME: 'START_GAME',
  STOP_GAME: 'STOP_GAME',

  PLAYER_CHANGED: 'PLAYER_CHANGED',
  SET_COLOR: 'SET_COLOR',
  CHECK_FIELD_FULL: 'CHECK_FIELD_FULL',
  UPDATE_PLAYERS_NAME: 'UPDATE_PLAYERS_NAME',
  HIDE_RESULTS: 'HIDE_RESULTS',
  SHOW_LEADERS: 'SHOW_LEADERS',
  HIDE_LEADERS: 'HIDE_LEADERS',

  RECEIVE_LEADERS: 'RECEIVE_LEADERS',
  RECEIVE_AUTH_REPLY: 'RECEIVE_AUTH_REPLY',
  COLOR_CHOOSED: 'COLOR_CHOOSED',

  FIELD_SIZE_CHANGED: 'FIELD_SIZE_CHANGED',
  CALC_CAPTURED: 'CALC_CAPTURED',
  RESET_PLAYERS: 'RESET_PLAYERS',
  UPDATE_GAME_ROOMS: 'UPDATE_GAME_ROOMS',
  NEW_ROOM_CREATED: 'NEW_ROOM_CREATED',

  WS_MESSAGE_UPDATE: 'WS_MESSAGE_UPDATE',

  PLAYER_CREATE_ROOM: 'PLAYER_CREATE_ROOM',
  PLAYER_JOIN_ROOM: 'PLAYER_JOIN_ROOM',
  PLAYER_SET_DOT: 'PLAYER_SET_DOT',
  PLAYER_GIVE_UP: 'PLAYER_GIVE_UP',
  THIS_PLAYER_GIVE_UP: 'THIS)PLAYER_GIVE_UP',
  GAME_OVER: 'GAME_OVER',
};
