const TYPES = {
  LOCAL_STORAGE: 'reduxDots',

  SEND_LOGOUT_REQUEST: 'SEND_LOGOUT_REQUEST',

  RECEIVE_LEADERS: 'RECEIVE_LEADERS',
  RECEIVE_AUTH_REPLY: 'RECEIVE_AUTH_REPLY',
  COLOR_CHOOSED: 'COLOR_CHOOSED',

  FIELD_SIZE_CHANGED: 'FIELD_SIZE_CHANGED',

  UPDATE_GAME_ROOMS: 'UPDATE_GAME_ROOMS',
  NEW_ROOM_CREATED: 'NEW_ROOM_CREATED',

  WS_MESSAGE_UPDATE: 'WS_MESSAGE_UPDATE',

  PLAYER_CREATE_ROOM: 'PLAYER_CREATE_ROOM',
  PLAYER_JOIN_ROOM: 'PLAYER_JOIN_ROOM',
  PLAYER_SET_DOT: 'PLAYER_SET_DOT',
  PLAYER_GIVE_UP: 'PLAYER_GIVE_UP',
  THIS_PLAYER_GIVE_UP: 'THIS)PLAYER_GIVE_UP',
  GAME_OVER: 'GAME_OVER',
  CLEAR_GAME_FIELD: 'CLEAR_GAME_FIELD',
  INTERRUPT_GAME_COMPONENT: 'INTERRUPT_GAME_COMPONENT',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',
  CLOSE_RESULTS: 'CLOSE_RESULTS',
};

export default TYPES;
