# Generated by Django 3.1.4 on 2021-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201208_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergame',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
