# Generated by Django 3.1.4 on 2021-01-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210127_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergame',
            options={},
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='updated_at',
        ),
    ]
