image: python:3.8

variables:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dots
  POSTGRES_DB: dots
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - venv

test-linter-react:
  stage: test
  image: node:latest
  cache: {}
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r django-dots/requirements.txt
  script:
    - pip install prospector[with_everything]
    - prospector --profile django-dots/profile.yaml

    
test-backend:
  services:  
    - postgres:latest
  stage: test
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r django-dots/requirements.txt
    - python3 django-dots/manage.py makemigrations
    - python3 django-dots/manage.py migrate
  script:
    - python django-dots/manage.py test api
    - python3 django-dots/manage.py test gamews.tests.WebsocketTestCase

