image: python:3.8

variables:
  POSTGRES_DB: db_name
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SECRET_KEY: (t&t5jd$a8iyd_v#5&eu%_j2fc1@)jl)y48wlqo^r8#s9xr45_
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - venv

test-linter-react:
  stage: test
  image: node:latest
  cache: {}
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r django-dots/requirements.txt
  script:
    - pip install prospector[with_everything]
    - prospector --profile django-dots/profile.yaml

    
test-backend:
  services:  
    - postgres:latest
  stage: test
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r django-dots/requirements.txt
  script:
    - python django-dots/manage.py test api
