image: python:3.8

variables:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dots
  POSTGRES_DB: dots
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
   - .cache/pip


before-script:
 - pip install -r django-dots/requirements.txt


test-linter-react:
  stage: test
  image: node:latest
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  script:
    - pip install prospector[with_everything]
    - prospector --profile django-dots/profile.yaml

    
test-backend:
  services:  
    - postgres:latest
  stage: test
  script:
    - python django-dots/manage.py test api
