build-job:
  stage: build
  script:
    - cd react-dots/
    - npm install
    - cd ..
    - virtualenv venv
    - . venv/bin/activate 
    - pip3 install -r django-dots/requirements.txt
    

test-linter-react:
  stage: test
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  script: 
    - prospector django-dots/


test-backend:
  stage: test
  script:
    - python3 django-dots/manage.py migrate
    - python3 django-dots/manage.py test


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."