test-linter-react:
  stage: test
  image: node:latest
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  image: python:3.8
  script: 
    - pip install virtualenv
    - virtualenv venv
    - . venv/bin/activate
    - pip3 install -r django-dots/requirements.txt
    - prospector django-dots/api

    
test-backend:
  services:  
    - postgres:latest
  variables:
    POSTGRES_DB: dots
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: test
  image: python:3.8
  
  script:
    - export DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dots
    - pip3 install virtualenv
    - virtualenv venv
    - . venv/bin/activate
    - pip3 install -r django-dots/requirements.txt
    - python3 django-dots/manage.py test api
