image: python:3.8

variables:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dots
  POSTGRES_DB: dots
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust


test-linter-react:
  stage: test
  image: node:latest
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  script:
    - pip install -r django-dots/requirements.txt
    - prospector django-dots/api

    
test-backend:
  services:  
    - postgres:latest
  stage: test
  script:
    - export DATABASE_URL=$DATABASE_URL
    - pip install -r django-dots/requirements.txt
    - python django-dots/manage.py test api
