build-job:
  stage: build
  script:
    
    - cd react-dots/
    - npm install


test-linter-react:
  stage: test
  image: node:latest
  script:
    - cd react-dots/
    - npm install
    - npm run lint


test-linter-django:
  stage: test
  image: python:3.8
  script: 
    - export DATABASE_URL=postgres://postgres:@postgres:5432/dots
    - pip install virtualenv
    - virtualenv venv
    - . venv/bin/activate
    - pip3 install -r django-dots/requirements.txt
    - prospector django-dots/


test-backend:
  stage: test
  script:
    - python3 django-dots/manage.py migrate
    - python3 django-dots/manage.py test


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."