build-job:
  stage: build
  script:
    - cd react-dots/


test-backend:
  stage: test
  script:
    - sudo apt-get install -y postgresql postgresql-client libpq-dev
    - sudo -u postgres psql -d dots

    - virtualenv venv
    - . venv/bin/activate 
    - pip3 install -r django-dots/requirements.txt
    
    - python3 django-dots/manage.py migrate
    - python3 django-dots/manage.py test


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."