# Generated by Django 3.1.1 on 2020-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=50)),
                ('looser', models.CharField(max_length=50)),
                ('win_score', models.DecimalField(decimal_places=1, max_digits=6)),
                ('lose_score', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
