# Generated by Django 3.1.1 on 2020-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match_equal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loose_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_score',
            field=models.IntegerField(),
        ),
    ]
