# Generated by Django 3.1.4 on 2020-12-07 13:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20201207_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together={('user', 'game_room')},
        ),
    ]
