# Generated by Django 3.1.4 on 2020-12-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201207_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together=set(),
        ),
    ]
