export const LOCAL_STORAGE = "DOTS_STATE";

export const SHOW_AUTH_FORM = "SHOW_AUTH_FORM";
export const HIDE_AUTH_FORM = "HIDE_AUTH_FORM";

export const SEND_REGISTER_REQUEST = "SEND_REGISTER_REQUEST";
export const SEND_LOGIN_REQUEST = "SEND_LOGIN_REQUEST";
export const SEND_LOGOUT_REQUEST = "SEND_LOGOUT_REQUEST";

export const CHANGE_PLAYER = "CHANGE_PLAYER";
export const DRAW_DOT = "DRAW_DOT";
export const CALC_SQUARE = "CALC_SQUARE";

export const ADD_TRACK = "ADD_TRACK";