export const LOCAL_STORAGE = "DOTS_STATE";

export const SHOW_AUTH_FORM = "SHOW_AUTH_FORM";
export const HIDE_AUTH_FORM = "HIDE_AUTH_FORM";

export const SEND_REGISTER_REQUEST = "SEND_REGISTER_REQUEST";
export const SEND_LOGIN_REQUEST = "SEND_LOGIN_REQUEST";
export const SEND_LOGOUT_REQUEST = "SEND_LOGOUT_REQUEST";

export const CHANGE_PLAYER = "CHANGE_PLAYER";
export const DRAW_DOT = "DRAW_DOT";
export const CALC_SQUARE = "CALC_SQUARE";

export const SHOW_SETTINGS = "SHOW_SETTINGS";
export const HIDE_SETTINGS = "HIDE_SETTINGS";
export const START_GAME = "START_GAME";
export const STOP_GAME = "STOP_GAME";

export const PLAYER_CHANGED = "PLAYER_CHANGED";
export const SET_COLOR = "SET_COLOR";
export const CHECK_FIELD_FULL = "CHECK_FIELD_FULL";
export const UPDATE_PLAYERS_NAME = "UPDATE_PLAYERS_NAME";
export const HIDE_RESULTS = "HIDE_RESULTS";
export const SHOW_LEADERS = "SHOW_LEADERS";
export const HIDE_LEADERS = "HIDE_LEADERS";

export const RECEIVE_LEADERS = "RECEIVE_LEADERS";
export const RECEIVE_AUTH_REPLY = "RECEIVE_AUTH_REPLY";